doctrine:
  orm:
    mappings:
      AcMarche\Presse:
        is_bundle: false
        dir: '%kernel.project_dir%/src/AcMarche/Presse/src/Entity'
        prefix: 'AcMarche\Presse'
        alias: AcMarche\Presse
