vich_uploader:
    db_driver: orm
    mappings:
        article_file:
            uri_prefix: /files
            upload_destination: '%kernel.project_dir%/public/files'
            namer:
                service: Vich\UploaderBundle\Naming\OrignameNamer
            directory_namer: AcMarche\Presse\Service\ArticleDirectoryNamer
        album_image:
            uri_prefix: /albums
            upload_destination: '%kernel.project_dir%/public/files'
            directory_namer: AcMarche\Presse\Service\AlbumDirectoryNamer
